export default {
  PHONE_NUMBER_NOT_FOUND: 'PHONE_NUMBER_NOT_FOUND',
  OTP_EXPIRY_SEC_NOT_DEFINED: 'OTP_EXPIRY_SEC_NOT_DEFINED',
  OTP_ERROR_WRONG_OR_EXPIRED: 'OTP_ERROR_WRONG_OR_EXPIRED',
  OTP_VERIFIED: 'OTP_VERIFIED',
};
